# Numpy Python Tutorial

In this tutorial, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples)
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

## Basic Python

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 2]   # Create a list
print (xs[1])
print (xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print (xs)

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print (xs)  

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print (x, xs) 

As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/2/tutorial/datastructures.html#more-on-lists).

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = [*range(5)]    # range is a built-in function that creates a list of integers
print(range(5))

print (nums)         # Prints "[0, 1, 2, 3, 4]"

In [ ]:
print (nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print (nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print (nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print (nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print (nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print (nums)         # Prints "[0, 1, 8, 9, 4]"

#### List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print (squares)

You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

List comprehensions can also contain conditions:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)

#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print (d['cat'])       # Get an entry from a dictionary; prints "cute"
print ('cat' in d)     # Check if a dictionary has a given key; prints "True"

In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print (d['fish'])      # Prints "wet"

In [ ]:
print (d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

In [ ]:
del d['fish']        # Remove an element from a dictionary
print (d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print ('cat' in animals)   # Check if an element is in a set; prints "True"
print ('fish' in animals)  # prints "False"


In [ ]:
animals.add('fish')      # Add an element to a set
print ('fish' in animals)

In [ ]:
animals.add('camel')       # Adding an element that is already in the set does nothing

animals.remove('fish')    # Remove an element from a set

print("\n",animals)

_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
T = (1,2,3)

for t in T:
    print(t)



In [ ]:
t[0] = 1

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])
print (type(a), a[0], a[1], a[2]) #Accessing individual elements
a[0] = 5                 # Change an element of the array
print (a)                  

In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print (b)

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print (a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print (b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print (c) 

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print (d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print (e)

In [ ]:
f = np.empty((2,2)) #Create an empty 2D array
print(f)

### Tensor

Tensors are generic names of matrices with arbitrary number of dimensions. In the context of tensors
dimensions are called "axies".
In deep learning, we generally manipulate tensors that are 0D to 4D, although you may go up to 5D if you process video data

### Rank

The number of axis of an array is called array rank. In numpy rank can be found from ndim property.
1D array are also called vector.
2D array are also called matrices.
and guess what - 3D array are collection of 2D matrices.

In [ ]:
a = np.array([1])
print(a.ndim)

a = np.array([1,2,3])
print(a.ndim)

a = np.array([[1,2,3],
              [4,5,6]])
print(a.ndim)

a = np.array([[[1,2,3],
               [4,5,6]],
              [[21,22,33],
               [44,55,66]]
             ])
print(a.ndim)

### Shape

This is a tuple of integers that describes how many dimensions the tensor has along each axis

In [ ]:
a = np.array([[1,3,4], #A matrix with 2 rows and 3 columns
              [6,7,8]])
print (a.shape)

a = np.array([[[1,2,3], #A tensor with 3 dimensions. 1rst dimension has 2 elements,  
               [4,5,6]], #2nd dimension has 2 elements and 3rd has 3 elements
              [[21,22,33],
               [44,55,66]]])
print (a.shape)

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print (x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array indexing

Numpy offers several ways to index into arrays.

In [ ]:
import numpy as np

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[2])

#Both are equal
print(arr2d[0][2])
print(arr2d[0, 2])

# Task

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
#Read the 0th position array

#Read the 1th position array

#Read the last array
arr2d[2]

# End Task

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# [1,2,3,4],[5,6,7,8]

print(a[:2]) #Will read 0th and 1rst rows

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3] #Multiple slices 
print (b)

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print (row_r1, row_r1.shape) 
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

# Task 

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]) #3x3 matrix

# Retireve rows(0,1) , column (1rst onward)

# Retireve Last row all columns

# Retireve all row but 0th and 1rst columns

# Retireve 1rst row but 0th and 1rst columns


# End Task

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2],
              [3, 4],
              [5, 6]])

# An example of integer array indexing.
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))

# The above example of integer array indexing is equivalent to this:
# The returned array will have shape (3,) and 
print (a[[0, 1, 2], [0, 1, 0]]) #Notice the double square brackets


In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

In [ ]:
#pass a list or ndarray of integers specifying the desired order

print(arr[[4, 3, 0, 6]])

print(arr[[-3, -5, -7]]) #Using negative indices selects rows from the end

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], 
              [3, 4],
              [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print (bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print (a[bool_idx])

# We can do all of the above in a single concise statement:
print (a[a > 2])

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x,y)

print('\n')

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print (x * y)
print (np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

`*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print (v.dot(w))
print (np.dot(v, w))

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print (x.dot(v))
print (np.dot(x, v))

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))

In [ ]:
#Can you guess the output
a = np.array([[ 5, 1 ,3],
              [ 1, 1 ,1],
              [ 1, 2 ,1]])

b = np.array([1, 2, 3])

c = np.arange(3)

print(a * b)

print(b.dot(c))

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print (x)
print (x.T)

In [ ]:
v = np.array([[1,2,3]])
print (v) 
print (v.T)

In [ ]:
v = np.ones((6))
print(v)

v = v.reshape(2,3)
print(v)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3],
              [4,5,6], 
              [7,8,9],
              [10, 11, 12]])

v = np.array([1, 0, 1])



In [ ]:
y = x + v  # Add x and v1 elementwise. 
print (y)

v1 = 2
y = x + v1  # Add x and v1 elementwise. Note that with broadcasting v1 has become a 3x4 matrix
print ("\n", y)



Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

### Why Numpy

In [ ]:
my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [ ]:
#Now let’s multiply each sequence by 2
%time for _ in range(10): my_arr2 = my_arr * 2 #Numpy processing time

%time for _ in range(10): my_list2 = [x * 2 for x in my_list] #loop based processing 

Numpy is generally 10 to 100 times faster